config/routes.rb
Agenda::Application.routes.draw do
  resources :eventos

end

app/models/evento.rb
class Evento < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  # GET /eventos
  # GET /eventos.xml
  def index
    @eventos = Evento.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @eventos }
    end
  end

  # GET /eventos/1
  # GET /eventos/1.xml
  def show
    @evento = Evento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @evento }
    end
  end

  # GET /eventos/new
  # GET /eventos/new.xml
  def new
    @evento = Evento.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @evento }
    end
  end

  # GET /eventos/1/edit
  def edit
    @evento = Evento.find(params[:id])
  end

  # POST /eventos
  # POST /eventos.xml
  def create
    @evento = Evento.new(params[:evento])

    respond_to do |format|
      if @evento.save
        format.html { redirect_to(@evento, :notice => 'Evento was successfully created.') }
        format.xml  { render :xml => @evento, :status => :created, :location => @evento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @evento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /eventos/1
  # PUT /eventos/1.xml
  def update
    @evento = Evento.find(params[:id])

    respond_to do |format|
      if @evento.update_attributes(params[:evento])
        format.html { redirect_to(@evento, :notice => 'Evento was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @evento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.xml
  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy

    respond_to do |format|
      format.html { redirect_to(eventos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :local %><br />
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :inicio %><br />
    <%= f.datetime_select :inicio %>
  </div>
  <div class="field">
    <%= f.label :termino %><br />
    <%= f.datetime_select :termino %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<h1>Listing eventos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Local</th>
    <th>Inicio</th>
    <th>Termino</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @eventos.each do |evento| %>
  <tr>
    <td><%= evento.nome %></td>
    <td><%= evento.local %></td>
    <td><%= evento.inicio %></td>
    <td><%= evento.termino %></td>
    <td><%= link_to 'Show', evento %></td>
    <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
    <td><%= link_to 'Destroy', evento, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @evento.nome %>
</p>

<p>
  <b>Local:</b>
  <%= @evento.local %>
</p>

<p>
  <b>Inicio:</b>
  <%= @evento.inicio %>
</p>

<p>
  <b>Termino:</b>
  <%= @evento.termino %>
</p>


<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agenda</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
                      teste
<%= yield %>

</body>
</html>